export const API_URL = `${import.meta.env.VITE_API_URL}/api/form/submit`

export const NATIONALITIES = [
  "Afghan","Albanian","Algerian","American","Andorran","Angolan","Argentine","Armenian",
  "Australian","Austrian","Bangladeshi","Belgian","Brazilian","British","Bulgarian","Canadian",
  "Chilean","Chinese","Colombian","Croatian","Czech","Danish","Dutch","Egyptian","Emirati",
  "Estonian","Finnish","French","German","Ghanaian","Greek","Hungarian","Icelandic","Indian",
  "Indonesian","Iranian","Irish","Israeli","Italian","Japanese","Kenyan","Korean","Latvian",
  "Lithuanian","Luxembourgish","Malaysian","Mexican","Moroccan","Nepalese","New Zealander",
  "Nigerian","Norwegian","Pakistani","Peruvian","Philippine","Polish","Portuguese","Qatari",
  "Romanian","Russian","Saudi","Singaporean","Slovak","Slovenian","South African","Spanish",
  "Sri Lankan","Swedish","Swiss","Thai","Turkish","Ukrainian","Vietnamese","Welsh","Zimbabwean",
]

export const COUNTRIES = [
  "Please Select",

  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",

  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",

  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",

  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",

  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",

  "Fiji",
  "Finland",
  "France",

  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",

  "Haiti",
  "Honduras",
  "Hungary",

  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",

  "Jamaica",
  "Japan",
  "Jordan",

  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",

  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",

  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",

  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",

  "Oman",

  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",

  "Qatar",

  "Romania",
  "Russia",
  "Rwanda",

  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",

  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",

  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",

  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",

  "Yemen",

  "Zambia",
  "Zimbabwe",

  "Other",
];


export const QUALIFICATIONS = [
  "Master Unlimited",
  "Chief Officer Unlimited",
  "Officer of the Watch (OOW) Unlimited",
  "Chief Engineer Unlimited",
  "Second Engineer Unlimited",
  "Engineering Officer of the Watch (EOOW) Unlimited",
  "None held",
  "Relevant Maritime Degree",
  "Other",
]

export const VESSEL_TYPES = [
  "Bulk Carrier",
  "Car Carrier",
  "Container vessel",
  "Drill Ship",
  "FSRU - Floating Storage Regasification Unit",
  "General Cargo",
  "In-land watercraft (barges, etc)",
  "LNG",
  "LPG",
  "Nil",
  "Offshore",
  "Oil/Chemical Tanker",
  "Passenger",
  "Rigs",
  "Ro Ro",
  "Steam",
  "Yacht",
  "Other",
]

export const SHORESIDE_EXPERIENCE = [
  "Class surveyor/auditor",
  "DPA",
  "Dry dock supervision",
  "Flag surveyor/auditor",
  "Lecturer (Maritime)",
  "Load Master",
  "P&I Surveyor",
  "Pilot",
  "Technical Officer",
  "Technician",
  "Vessel Manager/Superintendent",
  "Other",
]

export const SURVEYING_EXPERIENCE = [
  "Bunker survey",
  "Cargo (dry bulk)",
  "Cargo (wet)",
  "Hatch cover, hold condition & cleanliness surveys",
  "Incident investigations",
  "ISM Audits",
  "Marine Coating Inspections",
  "M032 Inspection",
  "Navigation Audits",
  "On-hire / Off-hire Inspections",
  "P&I Club surveys",
  "Pre-PSC Inspection",
  "Pre-Vetting Inspection",
  "SIRE Inspections",
  "Structural damage survey",
  "Warranty survey",
  "Other",
]

export const VESSEL_TYPE_SURVEYING_EXPERIENCE = [
  "Bulk Carrier",
  "Car Carrier",
  "Container vessel",
  "Drill Ship",
  "FSRU - Floating Storage Regasification Unit",
  "General Cargo",
  "In-land watercraft (barges, etc)",
  "LNG",
  "LPG",
  "Nil",
  "Offshore",
  "Oil/Chemical Tanker",
  "Passenger",
  "Rigs",
  "Ro Ro",
  "Steam",
  "Yacht",
  "Other",
]

export const ACCREDITATIONS = [
  "CDI (Chemical Distribution Inst.)",
  "Chartered Engineer",
  "Class Society Trained",
  "Flag State",
  "FROSIO (coatings)",
  "IIMS",
  "IMCA (CMID Approved)",
  "Lloyd's Maritime Academy",
  "NACE (coatings)",
  "OVID",
  "Rightship",
  "SIRE",
  "Other",
]

export const COURSES_COMPLETED = [
  "Diploma in Marine Surveying",
  "DPA Course",
  "IFIA Certification",
  "ISM ISPS MLC Lead Auditor",
  "Marine Surveying Diploma",
  "Navigational Assessment",
  "RightShip (RSIQ) Training",
  "SIRE 2.0 Training",
  "Other",
]
